# should be the same as the trigger source of the redpitaya
trigger_channel: 'ch1'
coincidence_channel: 'ch2'

# requirements for coincidence
offset: 0 # offset (of the trigger channel) in samples
window: 125 # window in samples (with rate 4 125 samples = 4us)


filename: 'coincidences'
update_interval: 5

# peak finding configuration
peak_config1:
  prominence: 200
  width: 10
  clip_value: 4095
  gradient_min: 0
  fluctuation: 10
  constant_length: 50

peak_config2:
  prominence: 200
  width: 10
  clip_value: 4095
  gradient_min: 0
  fluctuation: 5
  constant_length: 10


# coincidence spectrum configuration
coincidence_spectrum:
  filename: "coincidence_spectrum"
  x: ["height_trigger", 3000, 4095]
  y: ["height_coincidence", 3000, 4095]