# ip: https://redpitaya.readthedocs.io/en/latest/quickStart/first.html
ip: "rp-f0c38f.local"

# general configuration
sample_rate: 4 # This is the samples that are averaged into one. Possible are [1, 4, 8, 16, 32, 64, 128, 256]. Higher rates might be implemented
ch1_negated: false
ch2_negated: false

# data acquisition configuration
output_name: 'target/rpdaq' # name of the folder where the data is stored. Will be created and appended with YYYYMMDD-HHMM
events_per_loop: 1000 # number of events per loop. Due to networking there is always a short delay between loops
acquisition_mode: 'loops' # acquisition mode (time or loops or infinite)
acquisition_value: 100 # acquisition value in loops or minmum amount of time in seconds (last loop might be longer)



# oscilloscope configuration
trigger_source: 1 # channel on which the trigger lies (1 or 2)
trigger_slope: 'rising' # slope of the trigger (rising or falling)
trigger_mode: 'normal' # trigger mode (auto or normal)
trigger_level: 50 # trigger level in ADC Counts
pretrigger_samples: 100 # number of samples before the trigger
total_samples: 1000 # total number of samples

# signal generator configuration
rise_time: 10 # rise time in ns
fall_time: 10 # fall time in us
pulse_rate: 2000 # pulse rate in Hz
distribution: 'poisson' # distribution of the pulse rate (poisson or uniform)
spectrum_file: 'generators/quast.npy' # file with the spectrum of the signal generator (in csv format) see generators/create_spectrum.py for more information
start_generator: true # start the signal generator

