filename: "deltaT_spectrum"
update_interval: 5
update_interval_osc: .1
osc_range: 4096
spectrum:
  deltaT: [-1000, 1000, 2000]
  # deltaT_1_2: [-100, 1000, 1100]
  # deltaT_2_1: [-100, 1000, 1100]
  # deltaT_2_2: [-100, 1000, 1100]

